image: java:8-jdk

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - cd TourGuide
    - ./gradlew assemble
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}
    name: "$CI_JOB_NAME"
  only:
    - develop

test:
  stage: test
  script:
    - cd TourGuide
    - ./gradlew test
  only:
    - develop

