image: java:8-jdk
#gradle:alpine
#java:8-jdk

stages:
  - build
  - test
  #- deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# ./gradlew build
build:
  stage: build
  script:
    - cd TourGuide
    - ./gradlew assemble
  only:
    - develop

# gradle check
# gradle test
test:
  stage: test
  script:
    - cd TourGuide
    - ./gradlew check
  only:
    - develop

    #deploy:
    #stage: deploy
    #script:
    #- ./deploy

  #after_script:
  #- echo "End CI"
