version: "3.9"

services:

  tourguide:
    container_name:
    image:
    build:
    restart: always
    network_mode: host
    expose:
      - 8080

  microservice-gpsUtil:
    container_name:
    image:
    build:
    restart: always
    network_mode: host
    expose:
      - 8080

  microservice-rewardCentral:
    container_name:
    image:
    build:
    restart: always
    network_mode: host
    expose:
      - 8080

  microservice-tripPricer:
    container_name:
    image:
    build:
    restart: always
    network_mode: host
    expose:
      - 8080